E-LearningApplication/Backup1/Models/Groups.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.GroupMembers = new HashSet<GroupMembers>();
            this.Tests = new HashSet<Tests>();
            this.HomeworkAssignements = new HashSet<HomeworkAssignements>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupType { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual ICollection<GroupMembers> GroupMembers { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Tests> Tests { get; set; }
        public virtual ICollection<HomeworkAssignements> HomeworkAssignements { get; set; }
    }
}

E-LearningApplication/Backup1/Models/ViewModels/GroupsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_LearningApplication.Models.ViewModels {
    public class GroupsViewModel {
        public int GroupId { get; set; }

        [Display(Name="Group name")]
        [StringLength(30)]
        public string GroupName { get; set; }

        [Display(Name="Group description")]
        [StringLength(100)]
        public string GroupDescription { get; set; }

        [Display(Name="Group type")]
        [StringLength(30)]
        public string GroupType { get; set; }

        public Nullable<int> OwnerId { get; set; }

        public bool UserMembership { get; set; }
    }
}

E-LearningApplication/Backup1/Controllers/GroupsController.cs
using E_LearningApplication.CustomExceptions;
using E_LearningApplication.Models;
using E_LearningApplication.Models.DTOs;
using E_LearningApplication.Models.ViewModels;
using E_LearningApplication.Utils.LoggingUtils;
using E_LearningApplication.Utils.MailUtil;
using E_LearningApplication.ViewModelFactories;
using E_LearningApplication.ViewModelFactories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace E_LearningApplication.Controllers {
    [Authorize]
    public class GroupsController : Controller {
        #region Private fields

        //private readonly string apiMethodsUrl = "https://elearningservices.azurewebsites.net/";
        private readonly string apiMethodsUrl = "http://localhost:42175/";
        private ILoggingUtil logger = new NLogLogger();
        private IViewModelFactory viewModelFactory = new ViewModelFactory();

        #endregion

        //
        // GET: /Groups/

        public ActionResult Index() {
            return View();
        }

        #region Groups

        //
        // GET: /Groups/DisplayAllUnassociatedGroups()

        public ActionResult DisplayAllGroups() {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                var _userId = Session["UserId"];
                var _sessionUser = Convert.ToInt32(_userId);

                List<Groups> groups = new List<Groups>();
                using (var client = new HttpClient()) {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response = client.GetAsync("api/groups/GetAllUnassociatedGroups/?id=" + _sessionUser).Result;
                    if (response.IsSuccessStatusCode) {
                        var list = response.Content.ReadAsAsync<IEnumerable<Groups>>().Result;
                        if (list != null) {
                            groups = list.ToList();
                        }
                    }
                    else {
                        throw new CustomException("Could not complete the operation!");
                    }
                }

                List<GroupsViewModel> gvm = this.viewModelFactory.GetViewModel(groups);
                return View(gvm);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
        }

        //
        // GET: /Groups/DisplayAssociatedGroups()

        public ActionResult DisplayAssociatedGroups() {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                //get all associated groups to the currently logged in user
                List<Groups> groups = new List<Groups>();

                var _userId = Session["UserId"];
                var _sessionUser = Convert.ToInt32(_userId);

                #region get associated groups
                using (var client = new HttpClient()) {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response = client.GetAsync("api/groups/GetAssociatedGroups/?userId=" + _sessionUser).Result;
                    if (response.IsSuccessStatusCode) {
                        var list = response.Content.ReadAsAsync<IEnumerable<Groups>>().Result;
                        if (list != null) {
                            groups = list.ToList();
                        }
                    }
                    else {
                        throw new CustomException("Could not complete the operation!");
                    }
                }
                #endregion

                List<GroupsViewModel> gvm = this.viewModelFactory.GetViewModel(groups);
                return View(gvm);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
        }

        //
        // GET: /Groups/SearchAllGroups(groupName/groupDescription)

        public ActionResult SearchAllGroups(string searchString) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                List<Groups> groups = new List<Groups>();
                if (!string.IsNullOrWhiteSpace(searchString)) {
                    using (var client = new HttpClient()) {
                        client.BaseAddress = new Uri(this.apiMethodsUrl);
                        client.DefaultRequestHeaders.Accept.Add(
                            new MediaTypeWithQualityHeaderValue("application/json")
                            );
                        HttpResponseMessage response = client.GetAsync("api/groups/GetGroupByNameOrDescription/?searchTerm=" + searchString).Result;
                        if (response.IsSuccessStatusCode) {
                            var list = response.Content.ReadAsAsync<IEnumerable<Groups>>().Result;
                            if (list != null) {
                                groups = list.ToList();
                            }
                        }
                        else {
                            throw new CustomException("Could not complete the operation!");
                        }
                    }
                }
                List<GroupsViewModel> gvm = this.viewModelFactory.GetViewModel(groups);
                return View("DisplayAllGroups", gvm);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed!";
                return View("Error");
            }
        }

        //
        // GET: /Groups/SearchAssociatedGroups(groupName/groupDescription)

        public ActionResult SearchAssociatedGroups(string searchString) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                List<Groups> groups = new List<Groups>();
                if (!string.IsNullOrWhiteSpace(searchString)) {
                    using (var client = new HttpClient()) {
                        client.BaseAddress = new Uri(this.apiMethodsUrl);
                        client.DefaultRequestHeaders.Accept.Add(
                            new MediaTypeWithQualityHeaderValue("application/json")
                            );
                        HttpResponseMessage response = client.GetAsync("api/groups/GetGroupByNameOrDescription/?searchTerm=" + searchString).Result;
                        if (response.IsSuccessStatusCode) {
                            var list = response.Content.ReadAsAsync<IEnumerable<Groups>>().Result;
                            if (list != null) {
                                groups = list.ToList();
                            }
                        }
                        else {
                            throw new CustomException("Could not complete the operation!");
                        }
                    }
                }
                List<GroupsViewModel> gvm = this.viewModelFactory.GetViewModel(groups);
                return View("DisplayAssociatedGroups", gvm);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed!";
                return View("Error");
            }
        }

        //
        // GET: /Groups/CreateGroup()

        public ActionResult CreateGroup() {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            return View();
        }

        //
        // POST: /Groups/CreateGroup(groupViewModel)

E-LearningApplication/Backup1/Views/Groups/AddMemberToGroup.cshtml
@model Tuple<List<E_LearningApplication.Models.UserProfile>, int>

@{
    var selectList = new List<SelectListItem>();
    foreach (var item in Model.Item1) {
        selectList.Add(
        new SelectListItem() {
            Text = item.FirstName + " " + item.LastName + " - " + item.UserName,
            Value = item.UserId.ToString()
        });
    };
    selectList.Add(new SelectListItem() { Text = "Choose a new member...", Value = "-1", Selected = true });
}

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Add Group Member</h2>

    <div class="panel panel-body">
        @using (Html.BeginForm("AddMember", "Groups", new { groupId = Model.Item2 }, FormMethod.Post, new { @class = "panel-default" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            @Html.Label("Choose a member to add from the following list:", new { @class = "mb"})
            <br />
            @Html.DropDownList("newMember", selectList, new { @class = "btn btn-theme03 btn-sm mb" })

            <p>
                <input type="submit" class="btn btn-primary btn-sm" value="Add Member" />
            </p>
        }
    </div>
</div>

E-LearningApplication/Backup1/Views/Groups/CreateGroup.cshtml
@model E_LearningApplication.Models.ViewModels.GroupsViewModel

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Create Group</h2>

    <div class="panel panel-body">
        <div class="panel-default">
            @using (Html.BeginForm()) {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                
                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupName)
                </div>
                <div class="editor-field mb">
                    @Html.EditorFor(model => model.GroupName)
                    @Html.ValidationMessageFor(model => model.GroupName)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupDescription)
                </div>
                <div class="editor-field mb">
                    @Html.EditorFor(model => model.GroupDescription)
                    @Html.ValidationMessageFor(model => model.GroupDescription)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupType)
                </div>
                <div class="editor-field mb">
                    @Html.EditorFor(model => model.GroupType)
                    @Html.ValidationMessageFor(model => model.GroupType)
                </div>

                <p>
                    <input type="submit" class="btn btn-primary btn-sm" value="Create" />
                </p>
            }
        </div>
    </div>
</div>

E-LearningApplication/Backup1/Views/Groups/DisplayAllGroups.cshtml
@model IEnumerable<E_LearningApplication.Models.ViewModels.GroupsViewModel>

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display All Groups</h2>

    <div class="panel panel-body panel-default">
        <p>
            @Html.ActionLink("Show all groups", "DisplayAllGroups", "Groups")
        </p>

        <div class="mt">
            @using (Html.BeginForm("SearchAllGroups", "Groups", FormMethod.Get)) {

                <h5><i class="fa fa-search"></i> Search by</h5>
                <input type="text" name="searchString">
                <input type="submit" value="Search" class="btn btn-theme03 btn-xs" />
            }

        </div>
    </div>

    <div class="panel panel-body panel-default">
        <button type="button" class="btn btn-default">
            <span class="fa fa-plus-circle"></span>
            @Html.ActionLink("Create New Group", "CreateGroup")
        </button>

        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GroupName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupType)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupType)
                    </td>
                    <td>
                        @using (Html.BeginForm("SubscribeToGroup", "Groups", new { groupId = item.GroupId }, FormMethod.Post, new { title = "Subscribe to this group" })) {
                            @Html.AntiForgeryToken()

                            @Html.HiddenFor(modelItem => item.GroupId)
                            <button type="submit" class="btn btn-info btn-xs">
                                <i class="fa fa-star"></i> Subscribe
                            </button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

E-LearningApplication/Backup1/Views/Groups/DisplayAssociatedGroups.cshtml
@model IEnumerable<E_LearningApplication.Models.ViewModels.GroupsViewModel>

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display My Groups</h2>

    <div class="panel panel-body panel-default">
        <p>
            @Html.ActionLink("Show all my groups", "DisplayAssociatedGroups", "Groups")
        </p>

        <div class="mt">
            @using (Html.BeginForm("SearchAssociatedGroups", "Groups", FormMethod.Get)) {

                <h5><i class="fa fa-search"></i> Search by</h5>
                <input type="text" name="searchString">
                <input type="submit" value="Search" class="btn btn-theme03 btn-xs" />
            }

        </div>
    </div>

    <div class="panel panel-body panel-default">
        <button type="button" class="btn btn-default">
            <span class="fa fa-plus-circle"></span>
            @Html.ActionLink("Create New Group", "CreateGroup")
        </button>

        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GroupName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupType)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupType)
                    </td>
                    <td>
                        @Html.ActionLink("More...", "GroupDetails", new { id = item.GroupId }) |
                        @using (Html.BeginForm("UnsubscribeFromGroup", "Groups", new { groupId = item.GroupId }, FormMethod.Post, new { title = "Unsubscribe from the group" })) {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(modelItem => item.GroupId)
                            <button type="submit" class="btn btn-warning btn-xs">
                                <i class="fa fa-trash-o"></i> Unsubscribe
                            </button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

E-LearningApplication/Backup1/Views/Groups/DisplayGroupMembers.cshtml
@model Tuple<List<E_LearningApplication.Models.UserProfile>, int>

@{
    var viewModel = Model.Item1;
    var _groupId = Model.Item2;
}

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display Members</h2>

    <div class="panel panel-body panel-default">

        <button type="button" class="btn btn-default">
            <span class="fa fa-plus-circle"></span>
            @Html.ActionLink("Add new member", "AddMemberToGroup", new { groupId = _groupId })
        </button>

        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    User Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Middle Name
                </th>
                <th>
                    Email
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Item1) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MiddleName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @using (Html.BeginForm("RemoveMemberFromGroup", "Groups", new { groupId = _groupId, userId = item.UserId }, FormMethod.Post, new { title = "Remove member from the group" })) {
                            @Html.AntiForgeryToken()
                            
                            <button type="submit" class="btn btn-warning btn-xs">
                                <i class="fa fa-trash-o"></i> Delete from group
                            </button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

E-LearningApplication/Backup1/Views/Groups/EditGroup.cshtml
@model E_LearningApplication.Models.ViewModels.GroupsViewModel

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Edit Group Details</h2>

    <div class="panel panel-body">
        <div class="panel-default">
            @using (Html.BeginForm()) {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.GroupId)

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupName)
                </div>
                <div class="editor-field mb">
                    @Html.EditorFor(model => model.GroupName)
                    @Html.ValidationMessageFor(model => model.GroupName)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupDescription)
                </div>
                <div class="editor-field mb">
                    @Html.EditorFor(model => model.GroupDescription)
                    @Html.ValidationMessageFor(model => model.GroupDescription)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupType)
                </div>
                <div class="editor-field mb">
                    @Html.EditorFor(model => model.GroupType)
                    @Html.ValidationMessageFor(model => model.GroupType)
                </div>

                <p>
                    <input type="submit" class="btn btn-success btn-sm" value="Save" />
                </p>
            }
        </div>
    </div>
</div>

E-LearningApplication/Backup1/Views/Groups/GroupDetails.cshtml
@model E_LearningApplication.Models.ViewModels.GroupsViewModel

@{
    var _userId = Session["UserId"];
    var _sessionUser = Convert.ToInt32(_userId);
}

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Group Details</h2>

    <div class="panel panel-body panel-default">

        <div class="row mb col-lg-6">

            @Html.HiddenFor(model => model.GroupId)

            <div class="display-label">
                @Html.DisplayNameFor(model => model.GroupName)
            </div>
            <div class="display-field mb">
                @Html.DisplayFor(model => model.GroupName)
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.GroupDescription)
            </div>
            <div class="display-field mb">
                @Html.DisplayFor(model => model.GroupDescription)
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.GroupType)
            </div>
            <div class="display-field mb">
                @Html.DisplayFor(model => model.GroupType)
            </div>
        </div>

        <div class="col-lg-6">

            @if (_sessionUser == Model.OwnerId) {
                <div class="row mb">
                    <button class="btn btn-theme btn-xs" title="Edit group details">
                        <i class="fa fa-pencil"></i>
                        @Html.ActionLink("Edit", "EditGroup", new { id = Model.GroupId })
                    </button>
                </div>

                <div class="row mb">
                    @using (Html.BeginForm("DeleteGroup", "Groups", new { id = Model.GroupId }, FormMethod.Post, new { title = "Delete group" })) {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.GroupId)
                        <button type="submit" class="btn btn-danger btn-xs" title="Delete Group">
                            <i class="fa fa-trash-o"></i> Delete
                        </button>
                    }
                </div>

                <div class="row mb">
                    <button class="btn btn-theme03 btn-xs" title="Display group members">
                        <i class="fa fa-cogs"></i>
                        @Html.ActionLink("Manage Members", "DisplayGroupMembers", new { id = Model.GroupId })
                    </button>
                </div>
            }

            <div class="row mb">
                <button class="btn btn-warning btn-xs" title="Display group assignements">
                    <i class="fa fa-folder-open"></i>
                    @Html.ActionLink("View Assignements", "DisplayGroupAssignedHomework", "Homework", new { groupId = Model.GroupId }, new { title = "Display group assignements" })
                </button>
            </div>

            <div class="row mb">
                <button class="btn btn-warning btn-xs" title="Display group grades for assignements">
                    <i class="fa fa-folder-open"></i>
                    @Html.ActionLink("View Received Grades", "DisplayGroupReceivedGrades", "Grades", new { groupId = Model.GroupId }, new { title = "Display group grades for assignements" })
                </button>
            </div>

        </div>

    </div>
</div>

E-LearningApplication/Backup1/Views/Groups/Index.cshtml
<div class="form-panel">
    <h1><i class="fa fa-angle-right"></i> Home page</h1>

    <div>
        For all users:
        <ol>
            <li title="View all groups">@Html.ActionLink("View all groups", "DisplayAllGroups", "Groups")</li>
            <li title="View associated groups">@Html.ActionLink("View my groups", "DisplayAssociatedGroups", "Groups")</li>
            <li title="Create a new group">@Html.ActionLink("Create group", "CreateGroup", "Groups")</li>
        </ol>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>