E-LearningApplication/Backup1/Models/Homeworks.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homeworks
    {
        public Homeworks()
        {
            this.HomeworkAssignements = new HashSet<HomeworkAssignements>();
        }
    
        public int HomeworkId { get; set; }
        public string HomeworkCode { get; set; }
        public string HomeworkName { get; set; }
        public string HomeworkDescription { get; set; }
        public Nullable<System.DateTime> HomeworkDeadline { get; set; }
        public Nullable<decimal> HomeworkPoints { get; set; }
        public Nullable<System.DateTime> HomeworkAccessSpan { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CourseModuleId { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual CourseModule CourseModule { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<HomeworkAssignements> HomeworkAssignements { get; set; }
    }
}

E-LearningApplication/Backup1/Models/ViewModels/HomeworksViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_LearningApplication.Models.ViewModels {
    public class HomeworksViewModel {
        public int HomeworkId { get; set; }

        [Display(Name="Homework name")]
        [StringLength(30)]
        public string HomeworkName { get; set; }

        [Display(Name = "Short description of the homework")]
        [StringLength(30)]
        public string HomeworkDescription { get; set; }

        [Display(Name="Deadline")]
        public Nullable<System.DateTime> HomeworkDeadline { get; set; }

        [Display(Name="Homework points")]
        public Nullable<decimal> HomeworkPoints { get; set; }

        [Display(Name="Homework access time span")]
        public Nullable<System.DateTime> HomeworkAccessSpan { get; set; }

        public string HomeworkCode { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CourseModuleId { get; set; }
        public Nullable<int> OwnerId { get; set; }

    }
}

E-LearningApplication/Backup1/Controllers/HomeworkController.cs
using E_LearningApplication.CustomExceptions;
using E_LearningApplication.Models;
using E_LearningApplication.Models.DTOs;
using E_LearningApplication.Models.ViewModels;
using E_LearningApplication.Utils;
using E_LearningApplication.Utils.LoggingUtils;
using E_LearningApplication.ViewModelFactories;
using E_LearningApplication.ViewModelFactories.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace E_LearningApplication.Controllers {
    [Authorize]
    public class HomeworkController : Controller {
        #region Private fields

        //private readonly string apiMethodsUrl = "https://elearningservices.azurewebsites.net/";
        private readonly string apiMethodsUrl = "http://localhost:42175/";
        private ILoggingUtil logger = new NLogLogger();
        private IViewModelFactory viewModelFactory = new ViewModelFactory();

        #endregion

        /// <summary>
        /// Generates the homework code.
        /// </summary>
        /// <returns></returns>
        private static string GenerateHomeworkCode() {
            Guid guid = Guid.NewGuid();
            string guidString = Convert.ToBase64String(guid.ToByteArray());
            guidString = guidString.Replace("=", "");
            guidString = guidString.Replace("+", "");
            return guidString;

        }

        #region Prof functionalities

        //
        // GET: /Homework/DisplayAllCourseHomework(id = 0)
        [Authorize(Roles = "Prof")]
        public ActionResult DisplayAllCourseHomework(int id = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                List<Homeworks> homeworks = new List<Homeworks>();

                using (var client = new HttpClient()) {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response = client.GetAsync("api/homework/GetAllCourseHomework/?id=" + id).Result;
                    if (response.IsSuccessStatusCode) {
                        var list = response.Content.ReadAsAsync<IEnumerable<Homeworks>>().Result;
                        if (list != null) {
                            homeworks = list.ToList();
                        }
                    }
                    else {
                        throw new CustomException("Could not complete the operation!");
                    }
                }

                List<HomeworksViewModel> hvm = this.viewModelFactory.GetViewModel(homeworks);
                return View(hvm);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
        }

        //
        // GET: /Homework/DisplayAllCourseModuleHomework()
        [Authorize(Roles = "Prof")]
        public ActionResult DisplayAllCourseModuleHomework(int id = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                List<Homeworks> homeworks = new List<Homeworks>();

                using (var client = new HttpClient()) {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response = client.GetAsync("api/homework/GetAllCourseModuleHomework/?id=" + id).Result;
                    if (response.IsSuccessStatusCode) {
                        var list = response.Content.ReadAsAsync<IEnumerable<Homeworks>>().Result;
                        if (list != null) {
                            homeworks = list.ToList();
                        }
                    }
                    else {
                        throw new CustomException("Could not complete the operation!");
                    }
                }

                List<HomeworksViewModel> hvm = this.viewModelFactory.GetViewModel(homeworks);
                return View(hvm);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
        }

        //
        // GET: /Homework/CreateCourseHomework(id = 0)
        [Authorize(Roles = "Prof")]
        public ActionResult CreateCourseHomework(int id = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            ViewBag.CourseId = id;
            return View();
        }

        //
        // POST: /Homework/CreateCourseHomework(hwViewModel, courseId)
        [Authorize(Roles = "Prof")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCourseHomework(HomeworksViewModel homeworkViewModel, HttpPostedFileBase file, int courseId = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                var _userId = Session["UserId"];
                var _sessionUser = Convert.ToInt32(_userId);

                HomeworkDTO dto = new HomeworkDTO();
                dto.HomeworkAccessSpan = homeworkViewModel.HomeworkAccessSpan;
                dto.HomeworkDeadline = homeworkViewModel.HomeworkDeadline;
                dto.HomeworkDescription = homeworkViewModel.HomeworkDescription;
                dto.HomeworkId = homeworkViewModel.HomeworkId;
                dto.HomeworkName = homeworkViewModel.HomeworkName;
                dto.HomeworkPoints = homeworkViewModel.HomeworkPoints;
                dto.HomeworkCode = GenerateHomeworkCode();
                dto.CourseId = homeworkViewModel.CourseId;
                dto.CourseModuleId = homeworkViewModel.CourseModuleId;
                dto.OwnerId = _sessionUser;
                //save homework to db
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response =
                        client.PostAsJsonAsync("api/homework/AddHomework/?homework=", dto).Result;
                    if (!response.IsSuccessStatusCode)
                    {
                        throw new CustomException("Could not complete the operation!");
                    }

                    //save homework to drive
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/UploadedFiles"), fileName);
                    file.SaveAs(path);
                    //////upload homework
                    FileDTO fileDto = new FileDTO {parentId = courseId, fileName = dto.HomeworkCode, filePath = path};
                    HttpResponseMessage responseDrive =
                        client.PostAsJsonAsync("api/homework/UploadResourcesForHomework/?id=" + courseId, fileDto).Result;
                    if (!responseDrive.IsSuccessStatusCode)
                    {
                        throw new CustomException("Could not complete the operation!");
                    }
                }

                return RedirectToAction("DisplayAllCourseHomework", new { id = courseId });
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed!";
                return View("Error");
            }
        }

        //
        // GET: /Homework/CreateCourseModuleHomework(id = 0)
        [Authorize(Roles = "Prof")]
        public ActionResult CreateCourseModuleHomework(int id = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            ViewBag.CourseModuleId = id;
            return View();
        }

        private string GetUrlDownload(string FileId)
        {
            StringBuilder sb = new StringBuilder();

E-LearningApplication/Backup1/Views/Homework/AssignCourseHomework.cshtml
@model Tuple<List<E_LearningApplication.Models.UserProfile>, List<E_LearningApplication.Models.ViewModels.GroupsViewModel>, int, int>

@{
    var _homeworkId = Model.Item3;
    var _courseId = Model.Item4;
    
    var _usersList = new List<SelectListItem>();
    foreach (var item in Model.Item1) {
        _usersList.Add(
        new SelectListItem() {
            Text = item.FirstName + " " + item.LastName + " - " + item.UserName,
            Value = item.UserId.ToString()
        });
    };
    _usersList.Add(new SelectListItem() { Text = "Choose a student...", Value = "-1", Selected = true });

    var _groupsList = new List<SelectListItem>();
    foreach (var item in Model.Item2) {
        _groupsList.Add(
        new SelectListItem() {
            Text = item.GroupName,
            Value = item.GroupId.ToString()
        });
    };
    _groupsList.Add(new SelectListItem() { Text = "Choose a group...", Value = "-1", Selected = true });
}

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Add Assignement</h2>

    <div class="panel panel-body">
        @using (Html.BeginForm("CourseHomeworkAssignement", "Homework", new { id = _homeworkId, courseId = _courseId }, FormMethod.Post, new { @class = "panel-default" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            @Html.Label("Choose a recipient to assign the homework to:", new { @class = "mb"})
            <br />
            @Html.DropDownList("studentId", _usersList, new { @class = "btn btn-theme03 btn-sm mb" })
            <label class="mb">- OR -</label>
            @Html.DropDownList("groupId", _groupsList, new { @class = "btn btn-theme03 btn-sm mb" })

            <p>
                <input type="submit" class="btn btn-primary btn-sm" value="Add Assignement" />
            </p>
        }
    </div>
</div>

E-LearningApplication/Backup1/Views/Homework/AssignCourseModuleHomework.cshtml
@model Tuple<List<E_LearningApplication.Models.UserProfile>, List<E_LearningApplication.Models.ViewModels.GroupsViewModel>, int, int>

@{
    var _homeworkId = Model.Item3;
    var _courseModuleId = Model.Item4;

    var _usersList = new List<SelectListItem>();
    foreach (var item in Model.Item1) {
        _usersList.Add(
        new SelectListItem() {
            Text = item.FirstName + " " + item.LastName + " - " + item.UserName,
            Value = item.UserId.ToString()
        });
    };
    _usersList.Add(new SelectListItem() { Text = "Choose a student...", Value = "-1", Selected = true });

    var _groupsList = new List<SelectListItem>();
    foreach (var item in Model.Item2) {
        _groupsList.Add(
        new SelectListItem() {
            Text = item.GroupName,
            Value = item.GroupId.ToString()
        });
    };
    _groupsList.Add(new SelectListItem() { Text = "Choose a group...", Value = "-1", Selected = true });
}

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Add Assignement</h2>

    <div class="panel panel-body">
        @using (Html.BeginForm("CourseModuleHomeworkAssignement", "Homework", new { id = _homeworkId, courseModuleId = _courseModuleId }, FormMethod.Post, new { @class = "panel-default" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            @Html.Label("Choose a recipient to assign the homework to:")
            @Html.DropDownList("studentId", _usersList, new { @class = "btn btn-theme03" })
            @Html.Display("- OR -")
            @Html.DropDownList("groupId", _groupsList, new { @class = "btn btn-theme03" })

            <p>
                <input type="submit" class="btn btn-primary btn-sm" value="Add Assignement" />
            </p>
        }
    </div>
</div>

E-LearningApplication/Backup1/Views/Homework/CourseHomeworkDetails.cshtml
@model Tuple<E_LearningApplication.Models.ViewModels.HomeworksViewModel, List<E_LearningApplication.Models.ViewModels.HomeworkAssignementViewModel>, int>

@{
    var viewModel = Model.Item1;
    var viewModelList = Model.Item2;
    var _courseId = Model.Item3;

    var _userId = Session["UserId"];
    var _sessionUser = Convert.ToInt32(_userId);
}

<div class="form-panel">

    <h2><i class="fa fa-angle-right"></i> Homework Details</h2>
    <div class="panel panel-body panel-default mb">

        <div class="mb">
            <div class="col-lg-6">
                @Html.HiddenFor(model => viewModel.HomeworkId)
                @Html.HiddenFor(model => viewModel.HomeworkCode)

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkName)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkName)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkDescription)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkDescription)
                    <br />
                    <button class="btn btn-info btn-xs" title="Download course resources">
                        <i class="fa fa-arrow-down"></i>
                        @Html.ActionLink("Download", "DowloadCourseResource", "Homework", new { id = viewModel.HomeworkCode }, new { title = "Download homework"})
                    </button>
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkDeadline)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkDeadline)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkPoints)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkPoints)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkAccessSpan)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkAccessSpan)
                </div>
            </div>

            <div class="col-lg-6">
                @if (_sessionUser == viewModel.OwnerId) {
                    <div class="row mb">
                        <button class="btn btn-theme03 btn-xs" title="Edit group details">
                            <i class="fa fa-pencil"></i>
                            @Html.ActionLink("Edit", "EditCourseHomework", new { id = viewModel.HomeworkId, courseId = _courseId })
                        </button>
                    </div>

                    <div class="row mb">
                        @using (Html.BeginForm("DeleteCourseHomework", "Homework", new { id = viewModel.HomeworkId, courseId = _courseId }, FormMethod.Post, new { title = "Delete homework" })) {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger btn-xs" title="Delete homework">
                                <i class="fa fa-trash-o"></i> Delete
                            </button>
                        }
                    </div>
                }

                <div class="row mb">
                    <button class="btn btn-theme btn-xs" title="Add assignement for the homework">
                        <i class="fa fa-plus-square-o"></i>
                        @Html.ActionLink("Add Assignement", "AssignCourseHomework", "Homework", new { id = viewModel.HomeworkId, courseId = _courseId }, new { title = "Add assignement for the homework" })
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-body panel-default">
        <h2><i class="fa fa-angle-right"></i> Homework Assignements</h2>

        <table class="table table-striped table-hover mt">
            <tr>
                <th>Recipient</th>
                <th>Was Submitted?</th>
                <th></th>
            </tr>
            @foreach (var item in viewModelList) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RecipientName)
                    </td>
                    <td>
                        @if (item.AnswerId != null && item.AnswerId > 0) {
                            <span>Yes</span>
                        }
                        else {
                            <span>No</span>
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("UnassignCourseHomework", "Homework", new { homeworkId = viewModel.HomeworkId, assignementId = item.AssignementId, courseId = _courseId }, FormMethod.Post, new { title = "Unassign the homework from all the recipients" })) {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-theme02 btn-xs" title="Unassign homework">
                                <i class="fa fa-trash-o"></i> Unassign
                            </button>
                        }
                        @if (item.AnswerId != null && item.AnswerId > 0) {
                            <button class="btn btn-info btn-xs" title="Grade the homework">
                                <i class="fa fa-pencil-square-o"></i>
                                @Html.ActionLink("Grade", "GradeCourseHomework", "Grades", new { assignementId = item.AssignementId, homeworkId = item.HomeworkId, courseId = _courseId }, new { title = "Grade the homework" })
                            </button>
                        }
                        else {
                            <span>Answer not yet submitted</span>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>

</div>

E-LearningApplication/Backup1/Views/Homework/CourseModuleHomeworkDetails.cshtml
@model Tuple<E_LearningApplication.Models.ViewModels.HomeworksViewModel, List<E_LearningApplication.Models.ViewModels.HomeworkAssignementViewModel>, int>

@{
    var viewModel = Model.Item1;
    var viewModelList = Model.Item2;
    var _courseModuleId = Model.Item3;

    var _userId = Session["UserId"];
    var _sessionUser = Convert.ToInt32(_userId);
}

<div class="form-panel">

    <div class="panel panel-body panel-default">
        <h2><i class="fa fa-angle-right"></i> Homework Details</h2>

        <div class="mb">
            <div class="col-lg-6">
                @Html.HiddenFor(model => viewModel.HomeworkId)
                @Html.HiddenFor(model => viewModel.HomeworkCode)

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkName)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkName)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkDescription)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkDescription)
                    <button class="mt btn btn-info btn-xs" title="Download course resources">
                        <i class="fa fa-arrow-down"></i>
                        @Html.ActionLink("Download", "DowloadCourseResource", "Homework", new { id = viewModel.HomeworkCode }, new { title = "Download homework" })
                    </button>
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkDeadline)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkDeadline)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkPoints)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkPoints)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => viewModel.HomeworkAccessSpan)
                </div>
                <div class="display-field mb">
                    @Html.DisplayFor(model => viewModel.HomeworkAccessSpan)
                </div>
            </div>

            <div class="col-lg-6">
                @if (_sessionUser == viewModel.OwnerId) {
                    <div class="row mb">
                        <button class="btn btn-theme03 btn-xs" title="Edit group details">
                            <i class="fa fa-pencil"></i>
                            @Html.ActionLink("Edit", "EditCourseModuleHomework", new { id = viewModel.HomeworkId, courseModuleId = _courseModuleId })
                        </button>
                    </div>

                    <div class="row mb">
                        @using (Html.BeginForm("DeleteCourseModuleHomework", "Homework", new { id = viewModel.HomeworkId, courseModuleId = _courseModuleId }, FormMethod.Post, new { title = "Delete homework from module" })) {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger btn-xs" title="Delete homework from module">
                                <i class="fa fa-trash-o"></i> Delete
                            </button>
                        }
                    </div>
                }

                <div class="row mb">
                    <button class="btn btn-theme btn-xs" title="Add assignement for the homework">
                        <i class="fa fa-folder-open"></i>
                        @Html.ActionLink("Add Assignement", "AssignCourseModuleHomework", "Homework", new { id = viewModel.HomeworkId, courseModuleId = _courseModuleId }, new { title = "Add assignement for the homework" })
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-body panel-default">
        <h2><i class="fa fa-angle-right"></i> Homework Assignements</h2>

        <table class="table table-striped table-hover mt">
            <tr>
                <th>Recipient</th>
                <th>Was Submitted?</th>
                <th></th>
            </tr>
            @foreach (var item in viewModelList) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentId)
                    </td>
                    <td>
                        @if (item.AnswerId != null && item.AnswerId > 0) {
                            <span>Yes</span>
                        }
                        else {
                            <span>No</span>
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("UnassignCourseModuleHomework", "Homework", new { homeworkId = viewModel.HomeworkId, assignementId = item.AssignementId, courseModuleId = _courseModuleId }, FormMethod.Post, new { title = "Unassign the homework from all the recipients" })) {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-theme02 btn-xs" title="Unassign homework">
                                <i class="fa fa-trash-o"></i> Unassign
                            </button>
                        }
                        |
                        @if (item.AnswerId != null && item.AnswerId > 0) {
                            <button class="btn btn-info btn-xs" title="Grade the homework">
                                <i class="fa fa-pencil-square-o"></i>
                                @Html.ActionLink("Grade", "GradeCourseModuleHomework", "Grades", new { assignementId = item.AssignementId, homeworkId = item.HomeworkId, courseModuleId = _courseModuleId }, new { title = "Grade the homework" })
                            </button>
                        }
                        else {
                            <span>Answer not yet submitted</span>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>

</div>

E-LearningApplication/Backup1/Views/Homework/SubmitGroupHomework.cshtml
@model E_LearningApplication.Models.ViewModels.AssignementViewModel

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Submit Homework</h2>

    <div class="panel panel-default panel-body">

        <div class="mb col-lg-6">
            @Html.HiddenFor(item => Model.HomeworkId)

            <div class="editor-label">
                @Html.LabelFor(item => Model.HomeworkName)
            </div>
            <div class="editor-field mb">
                @Html.DisplayFor(item => Model.HomeworkName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(item => Model.HomeworkDescription)
            </div>
            <div class="editor-field mb">
                @Html.DisplayFor(item => Model.HomeworkDescription)
            </div>

            <div class="editor-label">
                @Html.LabelFor(item => Model.HomeworkDeadline)
            </div>
            <div class="editor-field mb">
                @Html.DisplayFor(item => Model.HomeworkDeadline)
            </div>

            <div class="editor-label">
                @Html.LabelFor(item => Model.HomeworkPoints)
            </div>
            <div class="editor-field mb">
                @Html.DisplayFor(item => Model.HomeworkPoints)
            </div>

            <div class="mb">
                <button class="btn btn-info btn-xs" title="Download homework description">
                    <i class="fa fa-arrow-down"></i>
                    @Html.ActionLink("Download", "DowloadCourseResource", "Prof", new { id = Model.HomeworkId }, new { title = "Download homework"})
                </button>
            </div>
        </div>

        <div class="mb col-lg-6">
            @using (Html.BeginForm("SubmitGroupHomework", "Homework", new { assignementId = Model.AssignementId, enctype = "multipart/form-data" }, FormMethod.Post)) {
                <div class="mb">
                    <label>Choose a file: </label>
                    <input type="file" name="file" class="btn btn-info" />
                </div>

                <p>
                    <input type="submit" value="Submit" class="btn btn-facebook btn-sm" />
                </p>
            }
        </div>
    </div>
</div>