E-LearningApplication/Backup/E-LearningApplication/Models/Grades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public Grades()
        {
            this.CourseModule = new HashSet<CourseModule>();
            this.HomeworkAssignements = new HashSet<HomeworkAssignements>();
        }
    
        public int GradeId { get; set; }
        public Nullable<decimal> GradeValue { get; set; }
        public Nullable<System.DateTime> Gradedatetime { get; set; }
    
        public virtual ICollection<CourseModule> CourseModule { get; set; }
        public virtual ICollection<HomeworkAssignements> HomeworkAssignements { get; set; }
    }
}

E-LearningApplication/Backup/E-LearningApplication/Models/ViewModels/GradesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_LearningApplication.Models.ViewModels {
    public class GradesViewModel {
        public int GradeId { get; set; }

        [Display(Name="Grade value")]
        public Nullable<decimal> GradeValue { get; set; }

        [Display(Name="Grading date")]
        public Nullable<System.DateTime> Gradedatetime { get; set; }

    }
}

E-LearningApplication/Backup/E-LearningApplication/Controllers/GradesController.cs
using E_LearningApplication.CustomExceptions;
using E_LearningApplication.Models;
using E_LearningApplication.Models.DTOs;
using E_LearningApplication.Models.ViewModels;
using E_LearningApplication.Utils.LoggingUtils;
using E_LearningApplication.ViewModelFactories;
using E_LearningApplication.ViewModelFactories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace E_LearningApplication.Controllers {
    [Authorize]
    public class GradesController : Controller {
        #region Private fields

        //private readonly string apiMethodsUrl = "https://elearningservices.azurewebsites.net/";
        private readonly string apiMethodsUrl = "http://localhost:42175/";
        private ILoggingUtil logger = new NLogLogger();
        private IViewModelFactory viewModelFactory = new ViewModelFactory();

        #endregion

        //
        // GET: /Grades/

        public ActionResult Index() {
            return View();
        }

        #region Prof functionalities

        //
        // GET: /Grades/GradeCourseHomework(courseId = 0, hwId = 0)
        [Authorize(Roles = "Prof")]
        public ActionResult GradeCourseHomework(int assignementId = 0, int homeworkId = 0, int courseId = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                //get the answer to be graded
                Answers answer = new Answers();
                using (var client = new HttpClient()) {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response = client.GetAsync("api/homework/GetAnswerForAssignement/?id=" + assignementId).Result;
                    if (response.IsSuccessStatusCode) {
                        var a = response.Content.ReadAsAsync<Answers>().Result;
                        if (a != null) {
                            answer.AnswerId = a.AnswerId;
                            answer.AnswerType = a.AnswerType;
                            answer.AnswerValue = a.AnswerValue;
                        }
                    }
                    else {
                        throw new CustomException("Could not complete the operation!");
                    }
                }
                Tuple<AnswersViewModel, int, int, int> viewModel = new Tuple<AnswersViewModel, int, int, int>(
                    this.viewModelFactory.GetViewModel(answer),
                    assignementId,
                    homeworkId,
                    courseId
                    );
                return View(viewModel);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed!";
                return View("Error");
            }
        }

        //
        // POST: /Grades/GradeCourseHomework(gradeValue = 0, courseId = 0)
        [Authorize(Roles = "Prof")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CourseHomeworkGrading(int assignementId = 0, int answerId = 0, int homeworkId = 0, int courseId = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                string gradeFromView = Request["gradeValue"];
                if (gradeFromView != null) {
                    decimal grade = Decimal.Parse(gradeFromView);
                    //create the grade dto to be passed to the api services
                    HomeworkGradeDTO dto = new HomeworkGradeDTO();
                    dto.Gradedatetime = System.DateTime.Now;
                    dto.GradeValue = grade;
                    dto.AnswerId = answerId;
                    dto.CourseId = courseId;
                    dto.HomeworkId = homeworkId;
                    dto.AssignementId = assignementId;

                    using (var client = new HttpClient()) {
                        client.BaseAddress = new Uri(this.apiMethodsUrl);
                        client.DefaultRequestHeaders.Accept.Add(
                            new MediaTypeWithQualityHeaderValue("application/json")
                            );
                        HttpResponseMessage response = client.PutAsJsonAsync("api/grades/GradeHomework/?assignementId=" + assignementId, dto).Result;
                        if (!response.IsSuccessStatusCode) {
                            throw new CustomException("Could not complete the operation!");
                        }
                    }

                    return RedirectToAction("DisplayAllCourseHomework", "Homework", new { id = courseId });
                }
                else {
                    ViewBag.Error = "Grade the submitted work!";
                    return View("Error");
                }
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed!";
                return View("Error");
            }
        }

        //
        // GET: /Grades/GradeCourseModuleHomework(courseModuleId = 0, hwId = 0)
        [Authorize(Roles = "Prof")]
        public ActionResult GradeCourseModuleHomework(int assignementId = 0, int homeworkId = 0, int courseModuleId = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                //get the answer to be graded
                Answers answer = new Answers();
                using (var client = new HttpClient()) {
                    client.BaseAddress = new Uri(this.apiMethodsUrl);
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                        );
                    HttpResponseMessage response = client.GetAsync("api/homework/GetAnswerForAssignement/?id=" + assignementId).Result;
                    if (response.IsSuccessStatusCode) {
                        var a = response.Content.ReadAsAsync<Answers>().Result;
                        if (a != null) {
                            answer.AnswerId = a.AnswerId;
                            answer.AnswerType = a.AnswerType;
                            answer.AnswerValue = a.AnswerValue;
                        }
                    }
                    else {
                        throw new CustomException("Could not complete the operation!");
                    }
                }
                Tuple<AnswersViewModel, int, int, int> viewModel = new Tuple<AnswersViewModel, int, int, int>(
                    this.viewModelFactory.GetViewModel(answer),
                    assignementId,
                    homeworkId,
                    courseModuleId
                    );
                return View(viewModel);
            }
            catch (CustomException ce) {
                this.logger.Trace(ce, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed! Try again.";
                return View("Error");
            }
            catch (Exception ex) {
                this.logger.Trace(ex, "Username: " + User.Identity.Name);
                ViewBag.Error = "Operation could not be completed!";
                return View("Error");
            }
        }

        //
        // POST: /Grades/GradeCourseModuleHomework(answerId = 0, homeworkId = 0, courseModuleId = 0)
        [Authorize(Roles = "Prof")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CourseModuleHomeworkGrading(int assignementId = 0, int answerId = 0, int homeworkId = 0, int courseModuleId = 0) {
            this.logger.Info("Entering: " + System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName + ": " + System.Reflection.MethodBase.GetCurrentMethod().Name + " --> " + User.Identity.Name);
            try {
                int grade = Int32.Parse(Request["gradeValue"]);
                if (grade > 0) {
                    //create the grade dto to be passed to the api services
                    HomeworkGradeDTO dto = new HomeworkGradeDTO();
                    dto.Gradedatetime = System.DateTime.Now;
                    dto.GradeValue = grade;
                    dto.AnswerId = answerId;
                    dto.CourseModuleId = courseModuleId;
                    dto.HomeworkId = homeworkId;
                    dto.AssignementId = assignementId;

                    using (var client = new HttpClient()) {
                        client.BaseAddress = new Uri(this.apiMethodsUrl);
                        client.DefaultRequestHeaders.Accept.Add(
                            new MediaTypeWithQualityHeaderValue("application/json")
                            );

E-LearningApplication/Backup/E-LearningApplication/Views/Grades/DisplayCourseGivenGrades.cshtml
@model IEnumerable<E_LearningApplication.Models.ViewModels.ReceivedGradeViewModel>

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display Course Grades</h2>

    <div class="panel panel-body panel-default">
        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkDeadline)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RecipientName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GradeValue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gradedatetime)
                </th>
            </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkDeadline)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RecipientName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GradeValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gradedatetime)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

E-LearningApplication/Backup/E-LearningApplication/Views/Grades/DisplayCourseModuleGivenGrades.cshtml
@model IEnumerable<E_LearningApplication.Models.ViewModels.ReceivedGradeViewModel>

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display Module Grades</h2>

    <div class="panel panel-body panel-default">
        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkDeadline)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RecipientName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GradeValue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gradedatetime)
                </th>
            </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkDeadline)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RecipientName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GradeValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gradedatetime)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

E-LearningApplication/Backup/E-LearningApplication/Views/Grades/DisplayGroupReceivedGrades.cshtml
@model IEnumerable<E_LearningApplication.Models.ViewModels.ReceivedGradeViewModel>

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display Group Grades</h2>

    <div class="panel panel-body panel-default">
        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkDeadline)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubjectCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AnswerValue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GradeValue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gradedatetime)
                </th>
            </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkDeadline)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubjectCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnswerValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GradeValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gradedatetime)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

E-LearningApplication/Backup/E-LearningApplication/Views/Grades/DisplayStudentReceivedGrades.cshtml
@model IEnumerable<E_LearningApplication.Models.ViewModels.ReceivedGradeViewModel>

<div class="form-panel">
    <h2><i class="fa fa-angle-right"></i> Display My Grades</h2>

    <div class="panel panel-body panel-default">
        <table class="table table-striped table-hover mt">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkDeadline)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HomeworkPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubjectCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AnswerValue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GradeValue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gradedatetime)
                </th>
            </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkDeadline)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeworkPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubjectCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnswerValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GradeValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gradedatetime)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

E-LearningApplication/Backup/E-LearningApplication/Views/Grades/GradeCourseHomework.cshtml
@model Tuple<E_LearningApplication.Models.ViewModels.AnswersViewModel, int, int, int>

@{
    var viewModel = Model.Item1;
    var _assignementId = Model.Item2;
    var _homeworkId = Model.Item3;
    var _courseId = Model.Item4;
}

<div class="form-panel">

    <div class="panel panel-body">
        @using (Html.BeginForm("CourseHomeworkGrading", "Grades", new { assignementId = _assignementId, answerId = viewModel.AnswerId, homeworkId = _homeworkId, courseId = _courseId }, FormMethod.Post, new { @class = "panel-default" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <h2><i class="fa fa-angle-right"></i> Submited Answer Details</h2>

            @Html.HiddenFor(model => viewModel.AnswerId)
            @Html.HiddenFor(model => viewModel.AnswerType)

            <div class="mb">
                <button class="btn btn-info btn-xs" title="Download course resources">
                    <i class="fa fa-arrow-down"></i>
                    @Html.ActionLink("Download Resources", "DowloadCourseResource", new { id = viewModel.AnswerId })
                </button>
            </div>

            <h2><i class="fa fa-angle-right"></i> Give A Grade</h2>
            <div class="display-field mb mt">
                <input type="text" name="gradeValue" />
            </div>
            
            <p>
                <input type="submit" class="btn btn-primary btn-sm" value="Add Grade" />
            </p>
        }

    </div>
</div>

E-LearningApplication/Backup/E-LearningApplication/Views/Grades/GradeCourseModuleHomework.cshtml
@model Tuple<E_LearningApplication.Models.ViewModels.AnswersViewModel, int, int, int>

@{
    var viewModel = Model.Item1;
    var _assignementId = Model.Item2;
    var _homeworkId = Model.Item3;
    var _courseModuleId = Model.Item4;
}

<div class="form-panel">

    <div class="panel panel-body">
        @using (Html.BeginForm("CourseModuleHomeworkGrading", "Grades", new { assignementId = _assignementId, answerId = viewModel.AnswerId, homeworkId = _homeworkId, courseIdModule = _courseModuleId }, FormMethod.Post, new { @class = "panel-default" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <h2><i class="fa fa-angle-right"></i> Submited Answer Details</h2>

            @Html.HiddenFor(model => viewModel.AnswerId)
            @Html.HiddenFor(model => viewModel.AnswerType)

            <div class="mb">
                <button class="btn btn-info btn-xs" title="Download course resources">
                    <i class="fa fa-arrow-down"></i>
                    @Html.ActionLink("Download Resources", "DowloadCourseResource", new { id = viewModel.AnswerId })
                </button>
            </div>

            <h2><i class="fa fa-angle-right"></i> Give A Grade</h2>
            <div class="display-field mb mt">
                <input type="text" name="gradeValue" />
            </div>
            <p>
                <input type="submit" class="btn btn-primary btn-sm" value="Add Grade" />
            </p>
        }

    </div>
</div>